version: 2.1

workflows:
    version: 2
    build_and_test:
      jobs:
        - deploy:
            context:
              - DOCKER
            filters:
              branches:
                only: master

jobs:
  deploy:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: docker build . -t angelvlc/google-play-publish
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker push angelvlc/google-play-publish
